---
- name: Add Repository GPG key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop: "{{ patroni_package_gpgkeys }}

- name: Add Patroni repositories
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    enabled: true
    gpgcheck: true
    baseurl: "{{ item.baseurl }}"
  loop: "{{ patroni_package_repos }}"

- name: Install required packages
  ansible.builtin.dnf:
    name: "{{ patroni_packages }}"
    state: present
   
